import { AgentEntity, RecurringTaskEntity, TagEntity, TaskEntity, TasksViewPayload } from "@/lib/workflow/types";

export const workflowAgents: AgentEntity[] = [
  { id: "agent-orbit", displayName: "Orbit", roleLabel: "Coder", presence: "online", avatarSeed: "O" },
  { id: "agent-rune", displayName: "Rune", roleLabel: "Analyst", presence: "online", avatarSeed: "R" },
  { id: "agent-mira", displayName: "Mira", roleLabel: "Writer", presence: "offline", avatarSeed: "M" },
  { id: "agent-kite", displayName: "Kite", roleLabel: "General", presence: "online", avatarSeed: "K" },
];

export const workflowTags: TagEntity[] = [
  { id: "tag-ui", label: "UI" },
  { id: "tag-ops", label: "Ops" },
  { id: "tag-review", label: "Review" },
  { id: "tag-content", label: "Content" },
  { id: "tag-automation", label: "Automation" },
  { id: "tag-priority", label: "Priority" },
];

export const workflowTasks: TaskEntity[] = [
  {
    id: "task-01",
    title: "Draft workflow release notes",
    brief: "Summarize UI-only behavior changes for internal review.",
    status: "todo",
    priority: "medium",
    assigneeAgentId: "agent-mira",
    tagIds: ["tag-content", "tag-review"],
    timeTrackingLabel: "Not started",
    recurringTemplateId: null,
  },
  {
    id: "task-02",
    title: "Polish kanban top bar spacing",
    brief: "Align filters and theme controls across tablet and desktop.",
    status: "todo",
    priority: "high",
    assigneeAgentId: "agent-orbit",
    tagIds: ["tag-ui", "tag-priority"],
    timeTrackingLabel: "12 minutes",
    startedAt: "2026-03-22T09:10:00.000Z",
  },
  {
    id: "task-03",
    title: "Audit waiting tasks for stale blockers",
    brief: "Review which blocked items still need human input.",
    status: "in_progress",
    priority: "urgent",
    assigneeAgentId: "agent-rune",
    tagIds: ["tag-ops", "tag-review"],
    timeTrackingLabel: "37 minutes",
    startedAt: "2026-03-22T08:40:00.000Z",
  },
  {
    id: "task-04",
    title: "Refresh sidebar agent presence copy",
    brief: "Tune labels so offline agents remain visible without looking unavailable.",
    status: "in_progress",
    priority: "medium",
    assigneeAgentId: "agent-kite",
    tagIds: ["tag-ui", "tag-content"],
    timeTrackingLabel: "21 minutes",
    startedAt: "2026-03-22T09:25:00.000Z",
  },
  {
    id: "task-05",
    title: "Investigate missing design tokens",
    brief: "Blocked by unresolved palette naming from architecture review.",
    status: "blocked",
    priority: "high",
    assigneeAgentId: "agent-orbit",
    tagIds: ["tag-ui", "tag-ops"],
    timeTrackingLabel: "1 hour",
    startedAt: "2026-03-22T07:55:00.000Z",
  },
  {
    id: "task-06",
    title: "Approve recurring task copy standards",
    brief: "Waiting on content sign-off before cards can be finalized.",
    status: "in_review",
    priority: "medium",
    assigneeAgentId: "agent-mira",
    tagIds: ["tag-content", "tag-review"],
    timeTrackingLabel: "44 minutes",
    startedAt: "2026-03-22T07:20:00.000Z",
  },
  {
    id: "task-07",
    title: "Ship dark theme token pass",
    brief: "Complete the first dark-ready palette pass for the shell.",
    status: "done",
    priority: "high",
    assigneeAgentId: "agent-orbit",
    tagIds: ["tag-ui", "tag-automation"],
    timeTrackingLabel: "2 hours",
    startedAt: "2026-03-22T05:00:00.000Z",
    completedAt: "2026-03-22T08:15:00.000Z",
  },
  {
    id: "task-08",
    title: "Reconcile dashboard summary copy",
    brief: "Match the lighter dashboard surface to the tasks-first information hierarchy.",
    status: "done",
    priority: "low",
    assigneeAgentId: "agent-kite",
    tagIds: ["tag-content"],
    timeTrackingLabel: "33 minutes",
    startedAt: "2026-03-21T16:00:00.000Z",
    completedAt: "2026-03-21T16:42:00.000Z",
  },
  {
    id: "task-09",
    title: "Verify adapter boundaries in selectors",
    brief: "Keep raw entities isolated from presentational models.",
    status: "done",
    priority: "medium",
    assigneeAgentId: "agent-rune",
    tagIds: ["tag-automation", "tag-review"],
    timeTrackingLabel: "51 minutes",
    startedAt: "2026-03-20T09:00:00.000Z",
    completedAt: "2026-03-20T09:51:00.000Z",
  },
];

export const recurringTasks: RecurringTaskEntity[] = [
  {
    id: "recurring-01",
    title: "Morning workflow sync digest",
    scheduleLabel: "Weekdays at 09:00 UTC",
    startsAt: "2026-03-01T09:00:00.000Z",
    nextRunAt: "2026-03-23T09:00:00.000Z",
    status: "active",
    defaultAgentId: "agent-rune",
  },
  {
    id: "recurring-02",
    title: "Release readiness checklist",
    scheduleLabel: "Every Tuesday at 14:00 UTC",
    startsAt: "2026-03-05T14:00:00.000Z",
    nextRunAt: "2026-03-24T14:00:00.000Z",
    status: "paused",
    defaultAgentId: "agent-kite",
  },
  {
    id: "recurring-03",
    title: "Knowledge base freshness review",
    scheduleLabel: "Fridays at 16:30 UTC",
    startsAt: "2026-03-07T16:30:00.000Z",
    nextRunAt: "2026-03-27T16:30:00.000Z",
    status: "active",
    defaultAgentId: "agent-mira",
  },
];

export const tasksViewFixture: TasksViewPayload = {
  tasks: workflowTasks,
  recurringTasks,
  agents: workflowAgents,
  availableTags: workflowTags,
  systemStatus: {
    server: "ready",
    label: "Mock adapter healthy. Scheduler and agent execution are presentation-only.",
  },
  userProfile: {
    displayName: "Avery Chen",
    plan: "Workspace reviewer",
    email: "avery.chen@example.com",
  },
};
